---
title: "14_power_analysis"
author: "Tobias Gerstenberg"
date: "2/15/2021"
output: 
  html_document:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
---

```{r setup, include=FALSE}
library("knitr")
library("DT")
library("janitor")
library("tidyverse")

opts_chunk$set(echo = TRUE)
theme_set(theme_classic() + 
            theme(text = element_text(size = 20),
                  panel.grid.major.y = element_line(color = "gray90")))
```

## Student feedback 

```{r echo=FALSE, message=FALSE}
read_csv("3-what-did-you-like-about-today-s-class-what-could.csv") %>% 
  datatable()
```
## PollEverywhere results 

```{r echo=FALSE, message=FALSE, results='hide', warning=FALSE}
df.pace = read_csv("2-how-was-the-pace-of-today-s-class.csv") %>% 
  rename(response = `Results Summary`) %>% 
  filter(row_number() > which(response == "Individual Results") + 1) %>% 
  clean_names() %>%  
  mutate(response = factor(response, levels = c("much too slow", "a little too slow", "just right", "a little too fast", "much too fast"),
                           labels = c("much\ntoo slow", "a little\ntoo slow", "just right", "a little\ntoo fast", "much\ntoo fast"))) %>% 
  count(response,
        .drop = F)

ggplot(data = df.pace,
       mapping = aes(x = response, y = n)) + 
  geom_bar(stat = "identity", fill = "lightblue", color = "black") +
  labs(y = "number of students", x = "", title = "How was the pace of today's class?")
```

```{r echo=FALSE, message=FALSE, results='hide'}
df.overall = read_csv("1-how-happy-were-you-with-today-s-class-overall.csv") %>% 
  clean_names() %>% 
  filter(!str_detect(response, "Click")) %>% # remove response outside of the click regions 
  mutate(response = as.numeric(response),
         response = factor(response, levels = 1:5,
                           labels = c("very\nunhappy", "unhappy", "neutral", "happy", "very\nhappy"))) %>% 
  count(response,
        .drop = F)

ggplot(data = df.overall,
       mapping = aes(x = response, y = n)) + 
  geom_bar(stat = "identity", aes(fill = response), color = "black", show.legend = F) +
  scale_fill_manual(values = c("red", "orange", "yellow", "lightgreen", "green")) +
  scale_y_continuous(breaks = seq(0, 40, 2)) + 
  labs(y = "number of students", x = "", title = "How happy were you with today's class overall?") +
  theme(title = element_text(size = 18))
```

## What to do next time



