---
title: "11 Linear Model 2"
author: "Tobias Gerstenberg"
date: "1/31/2020"
output: 
  html_document:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
---

```{r setup, include=FALSE}
library("knitr")
library("DT")
library("tidyverse")
opts_chunk$set(echo = TRUE)
theme_set(
  theme_classic() + 
    theme(
      text = element_text(size = 20),
      panel.grid.major.y = element_line(color = "gray90")
    ) 
)
```


## Homework 3

```{r echo=FALSE, message=FALSE, results='hide'}
df.hw3_happy = read_csv("how-do-you-feel-about-hw3.csv") %>% 
  set_names(c("response", "date")) %>% 
  filter(!str_detect(response, "Click")) %>% # remove response outside of the click regions 
  mutate(response = as.numeric(response),
         response = factor(response, levels = 1:5,
                           labels = c("very\nunhappy", "unhappy", "neutral", "happy", "very\nhappy"))) %>% 
  count(response) %>% 
  complete(response, fill = list(n = 0))

ggplot(data = df.hw3_happy,
       mapping = aes(x = response, y = n)) + 
  geom_bar(stat = "identity", aes(fill = response), color = "black", show.legend = F) +
  scale_fill_manual(values = c("red", "orange", "yellow", "lightgreen", "green")) +
  labs(y = "number of students", x = "", title = "How happy were you with hw3?") +
  theme(title = element_text(size = 18))
```

## What to do next time

- this class went well

