---
title: "Class 21"
author: "Tobias Gerstenberg"
date: ""
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    pandoc_args: ["--number-offset=20"]
bibliography: [packages.bib]
nocite: '@*'
---

```{r setup, include=FALSE}
# these options here change the formatting of how comments are rendered
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Bayesian data analysis

## Load packages and set plotting theme  

```{r load-packages, message=FALSE}
library("knitr")      # for knitting RMarkdown 
library("kableExtra") # for making nice tables
library("janitor")    # for cleaning column names
library("tidyverse")  # for wrangling, plotting, etc. 

# include references for used packages
knitr::write_bib(.packages(), "packages.bib") 
```

```{r set-theme}
theme_set(
  theme_classic() + #set the theme 
    theme(text = element_text(size = 20)) #set the default text size
)
```

## Likelihood contour plots 

```{r}
observation = 0.3

df.like = crossing(
  alpha = seq(from = 1, to = 10, by = 0.1),
  beta = seq(1, 10, 0.2)
) %>% 
  mutate(likelihood = map2_dbl(alpha, beta, ~ dbeta(observation, .x, .y)))

ggplot(data = df.like,
       mapping = aes(x = alpha,
                     y = beta)) +
  geom_raster(aes(fill = likelihood),
              interpolate = T) + 
  geom_contour(aes(z = likelihood, color = likelihood)) + 
  geom_point(data = df.like %>% 
               filter(row_number() == which.max(likelihood)),
             color = "red",
             size = 3) +
  scale_fill_gradient(low = "white", high = "black") +
  coord_cartesian(expand = F)

```



## Additional resources 

## Session info 

Information about this R session including which version of R was used, and what packages were loaded. 

```{r session}
sessionInfo()
```

## References


